# Generated by Django 5.1.4 on 2025-06-21 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("investments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GasTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "network",
                    models.CharField(
                        choices=[
                            ("mainnet", "Ethereum Mainnet"),
                            ("sepolia", "Sepolia Testnet"),
                            ("goerli", "Goerli Testnet"),
                            ("polygon", "Polygon"),
                        ],
                        max_length=20,
                    ),
                ),
                ("gas_price_gwei", models.BigIntegerField()),
                (
                    "gas_price_eth",
                    models.DecimalField(decimal_places=18, max_digits=20),
                ),
                ("block_number", models.BigIntegerField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="BlockchainTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("deploy", "Contract Deployment"),
                            ("mint", "NFT Minting"),
                            ("transfer", "Token Transfer"),
                            ("withdraw", "Fund Withdrawal"),
                            ("deposit", "Fund Deposit"),
                        ],
                        max_length=20,
                    ),
                ),
                ("transaction_hash", models.CharField(max_length=66, unique=True)),
                ("block_number", models.BigIntegerField(blank=True, null=True)),
                ("gas_used", models.BigIntegerField(blank=True, null=True)),
                ("gas_price", models.BigIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("failed", "Failed"),
                            ("reverted", "Reverted"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "network",
                    models.CharField(
                        choices=[
                            ("mainnet", "Ethereum Mainnet"),
                            ("sepolia", "Sepolia Testnet"),
                            ("goerli", "Goerli Testnet"),
                            ("polygon", "Polygon"),
                        ],
                        default="sepolia",
                        max_length=20,
                    ),
                ),
                ("from_address", models.CharField(max_length=42)),
                ("to_address", models.CharField(blank=True, max_length=42, null=True)),
                (
                    "value",
                    models.DecimalField(
                        blank=True, decimal_places=18, max_digits=20, null=True
                    ),
                ),
                ("data", models.TextField(blank=True)),
                ("receipt", models.JSONField(default=dict)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blockchain_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SmartContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("savings", "Savings Contract"),
                            ("investment", "Investment Contract"),
                            ("nft", "NFT Contract"),
                        ],
                        max_length=20,
                    ),
                ),
                ("contract_address", models.CharField(max_length=42, unique=True)),
                (
                    "network",
                    models.CharField(
                        choices=[
                            ("mainnet", "Ethereum Mainnet"),
                            ("sepolia", "Sepolia Testnet"),
                            ("goerli", "Goerli Testnet"),
                            ("polygon", "Polygon"),
                        ],
                        default="sepolia",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("deployed", "Deployed"),
                            ("pending", "Pending"),
                            ("failed", "Failed"),
                            ("paused", "Paused"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "deployment_hash",
                    models.CharField(blank=True, max_length=66, null=True),
                ),
                ("block_number", models.BigIntegerField(blank=True, null=True)),
                ("gas_used", models.BigIntegerField(blank=True, null=True)),
                ("gas_price", models.BigIntegerField(blank=True, null=True)),
                ("contract_abi", models.JSONField(default=list)),
                ("contract_bytecode", models.TextField(blank=True)),
                ("constructor_args", models.JSONField(default=list)),
                ("deployed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="smart_contracts",
                        to="accounts.child",
                    ),
                ),
                (
                    "investment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="smart_contracts",
                        to="investments.investment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="smart_contracts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NFT",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nft_type",
                    models.CharField(
                        choices=[
                            ("savings", "Savings Account NFT"),
                            ("achievement", "Achievement NFT"),
                            ("milestone", "Milestone NFT"),
                        ],
                        max_length=20,
                    ),
                ),
                ("token_id", models.BigIntegerField()),
                ("token_uri", models.URLField(blank=True)),
                ("metadata", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("minted", "Minted"),
                            ("pending", "Pending"),
                            ("failed", "Failed"),
                            ("burned", "Burned"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("mint_hash", models.CharField(blank=True, max_length=66, null=True)),
                ("block_number", models.BigIntegerField(blank=True, null=True)),
                ("minted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nfts",
                        to="accounts.child",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nfts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "smart_contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nfts",
                        to="blockchain.smartcontract",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("smart_contract", "token_id")},
            },
        ),
    ]
